name: publish-schemas-to-confluence
on: [push]
jobs:
  publish-schemas:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Bhacaz/docs-as-code-confluence@v1
        with:
          folder: 'schemas'
          parent-page-id: '327681' # The confluence page id where to write the output
          space-id: SD
          confluence-base-url: https://marziki.atlassian.net/wiki
          username: mohamed.arziki@bit.ly
          password: ${{ secrets.ATLASSIAN_TOKEN }}
          